### ISSUE TITLE
Centos6: Installation fails with `error: bad array initializer`

### ISSUE THREAD

**Issue by serverhorror** [hadley/readxl#78]
Hello,

I tried installing it but it fails with `error: bad array initializer`. Any help is appreciated.
```
> install.packages("readxl")
Installing package into ‘/apps/prod/R-3.1.1/R-3.1.1-sl-lib64’
(as ‘lib’ is unspecified)
trying URL 'http://bi-cranmirror.eu.boehringer.com/src/contrib/readxl_0.1.0.tar.gz'
Content type 'application/x-gzip' length 316876 bytes (309 Kb)
opened URL
==================================================
downloaded 309 Kb

* installing *source* package ‘readxl’ ...
** package ‘readxl’ successfully unpacked and MD5 sums checked
** libs
g++ -I/apps/prod/R-3.1.1/R-3.1.1-sl/lib64/R/include -DNDEBUG -Iunix -I. -I/usr/local/include -I"/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include"  -std=c++0x -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -I/apps/prod/R-3.1.1/R-3.1.1-sl/lib64/R/include -DNDEBUG -Iunix -I. -I/usr/local/include -I"/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include"  -std=c++0x -fpic  -g -O2  -c XlsWorkBook.cpp -o XlsWorkBook.o
In file included from /apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/RcppCommon.h:74,
                 from /apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp.h:27,
                 from XlsWorkBook.cpp:1:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int N = 2]’:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/exceptions.h:207:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&) [with T1 = std::string, T2 = int]’
CellType.h:32:   instantiated from here
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int N = 1]’:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/exceptions.h:256:   instantiated from ‘void Rcpp::stop(const char*, const T1&) [with T1 = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
XlsWorkBook.h:28:   instantiated from here
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, char*, int N = 3]’:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, char*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, char*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, char*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = char*]’
XlsWorkSheet.h:128:   instantiated from here
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, double, int N = 3]’:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, double]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, double]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, double]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = double]’
XlsWorkSheet.h:139:   instantiated from here
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, xls::BYTE*, int N = 3]’:
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, xls::BYTE*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, xls::BYTE*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, xls::BYTE*]’
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = xls::BYTE*]’
XlsWorkSheet.h:147:   instantiated from here
/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
make: *** [XlsWorkBook.o] Error 1
ERROR: compilation failed for package ‘readxl’
* removing ‘/apps/prod/R-3.1.1/R-3.1.1-sl-lib64/readxl’

The downloaded source packages are in
        ‘/tmp/RtmpXUeQcM/downloaded_packages’
Warning message:
In install.packages("readxl") :
  installation of package ‘readxl’ had non-zero exit status
```

OS

```
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: Scientific
Description:    Scientific Linux release 6.6 (Carbon)
Release:        6.6
Codename:       Carbon
```

**Comment by hadley** [comment]
This appears to be an Rcpp problem. Any thoughts @jjallaire?

**Comment by jjallaire** [comment]
@kevinushey Any reason you can think this wouldn't compile on older GCC (this is on CentOS 6 which uses GCC 4.4)

@hadley Rcpp itself compiles fine on CentOS 6 / GCC 4.4 so my guess is that this error is tickled by a template instantiation associated with Rcpp::warning that doesn't work on GCC 4.4. Kevin can confirm, but there may not be anything we can do about this however you can probably work around it by passing different arguments to Rcpp::warning.

**Comment by hadley** [comment]
@jjallaire I wonder if it's tickled by the `-std=c++0x`

**Comment by jjallaire** [comment]
Very possibly it is! Kevin, a trick we just started using on CRAN (to get
around the long long warnings, etc.) is to do this:

PKG_CPPFLAGS += $(CXX1XSTD)

Which results in R using whatever -std flag is supported by the target
compiler (including none for older versions of GCC). Hadley is speculating
that the addition of -std=c++0x this results in may be causing problems in
compiling the tinyformat code.

**Comment by homerhanumat** [comment]
I will be interested in how this is resolved.  I've got the same problem on the Server at my College.

**Comment by rvij** [comment]
I got similar error on Redhat Linux 6.5, can you please update the workaround for this problem. Thanks

**Comment by andrewcstewart** [comment]
+1

**Comment by kevinushey** [comment]
`tinyformat` does attempt to detect C++11 support [here](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/utils/tinyformat.h#L147-L157); it's entirely possible that it's detecting C++11 support in an older compiler that does not actually have enough guts available to make sure compilation works.

What we (probably) could do is just strip out all of the C++11-related code for the embedded `tinyformat` in Rcpp; presumedly then these old compilers wouldn't try to use C++11 features they don't yet fully implement.

I'll make that change on an Rcpp branch and send a PR.

**Comment by kevinushey** [comment]
Actually, looking more closely, it seems like it would be sufficient for us to just define `TINYFORMAT_NO_VARIADIC_TEMPLATES` (to suppress the check).

**Comment by kevinushey** [comment]
This is now fixed on the Rcpp side. A local fix that could be used for `readxl` in the interm would involve placing a forward define `#define TINYFORMAT_NO_VARIADIC_TEMPLATES` into each compilation unit of `readxl` before `Rcpp.h` is included.

**Comment by mdavy86** [comment]
:+1: Works

**Comment by rvij** [comment]
Works for me too! Thanks 
I just ran the command on Redhat linux 6.5

devtools::install_github("hadley/readxl")

and it installed successfully without complaining anymore.

**Comment by homerhanumat** [comment]
The patched worked on our CentOS server.  Thanks!

**Comment by serverhorror** [comment]
Do I read that right: Once I update RcppCore/Rcpp#290 with the referenced patch `readxl` should be good to go?

**Comment by mdavy86** [comment]
Yes just reinstall the dependency `Rcpp` and `readxl`

```r
devtools::install_github("RcppCore/Rcpp")
devtools::install_github("hadley/readxl")
```
