### ISSUE TITLE
Cannot install readxl in R 4.4.3

### ISSUE THREAD

**Issue by Rosemarijn96** [hadley/readxl#797]
I am having a lot of trouble installing readxl in R on a new work computer. I will paste the error and session info bellow and explain what I have already tried to resolve this.

<html>
<body>

> sessionInfo() R version 4.4.3 (2025-02-28 ucrt) Platform: x86_64-w64-mingw32/x64 Running under: Windows 11 x64 (build 26100)  Matrix products: default   locale: [1] LC_COLLATE=City_Country.utf8  LC_CTYPE=City_Country.utf8    LC_MONETARY=City_Country.utf8 LC_NUMERIC=C                       [5] LC_TIME=City_Country.utf8      time zone: Europe tzcode source: internal  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached):  [1] compiler_4.4.3    fastmap_1.2.0     cli_3.6.6         htmltools_0.5.9   tools_4.4.3       otel_0.2.0        rstudioapi_0.19.0 yaml_2.3.12        [9] rmarkdown_2.31    knitr_1.51        xfun_0.60         digest_0.6.39     rlang_1.3.0       evaluate_1.0.5
--
 
> | >
>

</body>
</html>

> remotes::install_version("readxl",version="1.5.0")
Downloading package from url: https://cran.rstudio.com/src/contrib/readxl_1.5.0.tar.gz
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: progress (1.2.1 -> 1.2.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
progress (1.2.1 -> 1.2.3) [CRAN]
Installing 1 packages: progress
Installing package into ‘X:/App/Documenten/R/win-library/4.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/progress_1.2.3.tar.gz'
Content type 'application/x-gzip' length 30499 bytes (29 KB)
downloaded 29 KB

* installing *source* package 'progress' ...
** package 'progress' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (progress)

The downloaded source packages are in
	‘C:\Users\local\Temp\Rtmpo10MCs\downloaded_packages’
Installing package into ‘X:/App/Documenten/R/win-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package 'readxl' ...
** package 'readxl' successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: 'gcc.exe (GCC) 13.3.0'
using C++ compiler: 'G__~1.EXE (GCC) 13.3.0'
g++ -std=gnu++17  -I"C:/PROGRA~1/R/R-44~1.3/include" -DNDEBUG -Iwindows -I. -D__USE_MINGW_ANSI_STDIO -I'X:/App/Documenten/R/win-library/4.4/cpp11/include' -I'X:/App/Documenten/R/win-library/4.4/progress/include'   -I"C:/ProgramData/App-V/E70CFEDB-0275-4C43-9FB3-55B94DF8C45D/56735A42-0C2E-4C40-B998-8C82DA371091/root/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cpp11.cpp -o cpp11.o
In file included from c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\bits\ios_base.h:46,
                 from c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\streambuf:43,
                 from c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\bits\streambuf_iterator.h:35,
                 from c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\iterator:66,
                 from X:/App/Documenten/R/win-library/4.4/cpp11/include/cpp11/r_vector.hpp:10,
                 from X:/App/Documenten/R/win-library/4.4/cpp11/include/cpp11/list.hpp:9,
                 from X:/App/Documenten/R/win-library/4.4/cpp11/include/cpp11/data_frame.hpp:11,
                 from X:/App/Documenten/R/win-library/4.4/cpp11/include/cpp11.hpp:7,
                 from X:/App/Documenten/R/win-library/4.4/cpp11/include/cpp11/declarations.hpp:13,
                 from cpp11.cpp:5:
c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\system_error:41:10: fatal error: bits/error_constants.h: No such file or directory
   41 | #include <bits/error_constants.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-44~1.3/etc/x64/Makeconf:296: cpp11.o] Error 1
ERROR: compilation failed for package 'readxl'
* removing 'X:/App/Documenten/R/win-library/4.4/readxl'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/LOCAL_~1/Temp/Rtmpo10MCs/remotes398436b555cd/readxl’ had non-zero exit status

I have tried to install a specific version, have already updated the progress and cpp11 packages as suggested in other questions here (https://github.com/tidyverse/vroom/issues/538). I have also downloaded the package and went for manual installation but this all resulted in the same problem. Does anyone know what would be the best way to solve this? Am I missing something here? Other packages show no problem so far.

**Comment by Rosemarijn96** [comment]
I get the same error message when trying to install stringi (which is needed when using tidyverse if I understand correctly) 

In file included from icu74/common/umutex.h:24,
                 from icu74/common/mutex.h:27,
                 from icu74/common/brkeng.cpp:32:
c:\programdata\app-v\e70cfedb-0275-4c43-9fb3-55b94df8c45d\56735a42-0c2e-4c40-b998-8c82da371091\root\rtools44\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\13.3.0\include\c++\condition_variable:41:10: fatal error: bits/error_constants.h: No such file or directory
   41 | #include <bits/error_constants.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-44~1.3/etc/x64/Makeconf:296: icu74/common/brkeng.o] Error 1
ERROR: compilation failed for package 'stringi'
* removing 'X:/App/Documenten/R/win-library/4.4/stringi'
Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Local\Temp\RtmpQlXt2G\downloaded_packages’

**Comment by jennybc** [comment]
This is a very high-level observation, but the fact that you're struggling with both readxl and stringi suggests that you're just not setup yet to build R packages from source.

You're being forced to do this because of being on R 4.4.3. If you were using R 4.6 (current) or even 4.5 (1 minor version behind current), you'd be able to get install pre-compiled binary packages. So if there is any way to get more current, that is my strong suggestion.

**Comment by Rosemarijn96** [comment]
Thank you for the reply! I think the problem was that there were two versions of R installed on my computer at the same time. I am now working in R4.6.0 and everything installs just fine.

**Comment by jennybc** [comment]
Glad it's sorted out.
